---
driver:
  name: 'hyperv'
  memory_startup_bytes: 2147483648
  processor_count: 2
  vm_generation: 2
  parent_vhd_folder: 'C:/Users/Public/Documents/Hyper-V/Virtual hard disks'
  parent_vhd_name: 'windows-8.1-pro.vhdx'
  vm_switch: 'hyperv-switch'

provisioner:
  name: chef_zero

transport:
  username: 'test-kitchen'
  password: 'test-kitchen'
  connection_retries: 10
  connection_retry_sleep: 5

verifier:
  name: pester

platforms:
  - name: windows-8.1-pro

suites:
  - name: default
    run_list:
      - recipe[housepub-win8-services::default]
    attributes:
